# Generated by Django 2.2.1 on 2019-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Barang', models.CharField(max_length=100)),
                ('Stok_Barang', models.CharField(max_length=50)),
                ('Tanggal_masuk', models.CharField(max_length=50)),
                ('Keterangan', models.TimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataKaryawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.CharField(max_length=100)),
                ('Tgl_Lahir', models.DateTimeField(max_length=50)),
                ('Jenis_kelamin', models.CharField(max_length=50)),
                ('Alamat', models.CharField(max_length=50)),
                ('No_Hp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_UKM', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('No_HP', models.CharField(max_length=20)),
                ('Alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sportukmapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ukmapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
