# Generated by Django 2.2.1 on 2019-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ukmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databarang',
            name='Keterangan',
        ),
        migrations.AlterField(
            model_name='databarang',
            name='Tanggal_masuk',
            field=models.DateField(max_length=50),
        ),
    ]
